### ISSUE TITLE
Some comments on your DG

### ISSUE THREAD

**Issue by siuhian** [AY2021S1-CS2113-T16-4/tp#60]
- [x] Could consider removing the phrase {Describe the design and implementation of the product. Use UML diagrams and short code snippets where applicable.}

- [x] 1. Try to list out all the command classes instead of using a shortcut. Another way is to just list the important commands needed for your application. Don't do this.

- [x] 2. Try to use the notation taught in class. Could remove the unique keyword

![image](https://user-images.githubusercontent.com/42374522/97597455-ce853e80-1a40-11eb-892e-bd43aee9d176.png)

- [ ] Try to keep diagram simple, the aim is to make it comprehensible not comprehensive

![image](https://user-images.githubusercontent.com/42374522/97597627-03919100-1a41-11eb-99b1-9f88a61bd35c.png)

- [x] Try not to use notation not taught in class like the break frame, could maybe change to an opt frame that returns if the condition is met. Same goes for the following diagrams that uses break.

![image](https://user-images.githubusercontent.com/42374522/97598380-dbeef880-1a41-11eb-963c-b98fe4ebe5bd.png)

- [ ] Diagram is far too small to be readable. I would suggest to break the complicated sequence diagram into multiple smaller sequence diagrams to help improve readability and understandability.

![image](https://user-images.githubusercontent.com/42374522/97598781-46079d80-1a42-11eb-9592-41584d53d3e8.png)

**Comment by TanJunHong** [comment]
Fixed.
