### ISSUE TITLE
JAR file was unable to run during PE dry run

### ISSUE THREAD

**Issue by HengFuYuen** [AY2021S1-CS2113-T16-4/tp#61]
![image](https://user-images.githubusercontent.com/60005925/97679601-6da54700-1ad0-11eb-8845-8208fef8876c.png)

**Comment by TanJunHong** [comment]
Reuploaded fix jar file.
Please let me know if there are still issues.

**Comment by HengFuYuen** [comment]
I am able to run the JAR file successfully now! All the best!
