### ISSUE TITLE
Unable to run JAR file during PE dry run

### ISSUE THREAD

**Issue by gmit22** [AY2021S1-CS2113-T16-4/tp#62]
The following error was shown `no main manifest attribute, in tp.jar` on executing `java -jar tp.jar`

**Comment by gmit22** [comment]
<img width="243" alt="Capture" src="https://user-images.githubusercontent.com/59180102/97679876-db934380-1abb-11eb-99bd-bc375d47b1c1.PNG">

**Comment by TanJunHong** [comment]
Reuploaded fixed jar file.
Please let me know if there are any more issues.
Thank you.
