### ISSUE TITLE
Jar file does not run

### ISSUE THREAD

**Issue by hermanthong** [AY2021S1-CS2113-T16-4/tp#63]
Cannot run jar file, no main manifest attribute
![nomanifest.PNG](https://raw.githubusercontent.com/rashien3/ped/main/files/178a0606-8d3d-4570-9dce-b54597928aaa.PNG)

**Comment by TanJunHong** [comment]
Long time no see Herman.
Thanks for the bug report, and sorry for the inconvenience,
Reuploaded fixed jar file.
If possible, please test the new jar file, and create another issue if it does not work.
Thank you!
